### ISSUE TITLE
'NoneType' object has no attribute 'get_complete_glossary'

### ISSUE THREAD

**Issue by khrizo** [jrief/djangocms-cascade#166]
django cms: 3.3.0
django: 1.8.3
cms cascade: 0.8.4 (migrated from 0.7.3)

When trying to add an image, gallery, carousell or picture, everything else works fine.

/lib/python2.7/cmsplugin_cascade/bootstrap3/image.py in get_form utils.reduce_breakpoints(self, 'responsive-heights') ...
/lib/python2.7/cmsplugin_cascade/bootstrap3/utils.py in reduce_breakpoints complete_glossary = plugin.get_parent_instance().get_complete_glossary() ...

Thanks in advanced.

**Comment by jrief** [comment]
where do you add it?

**Comment by khrizo** [comment]
trying to add it to **container > row > column**

**Comment by olligopoly** [comment]
I'm also getting the exact same with a fresh install of Django CMS and Cascade. Django version is 1.9.3.

'NoneType' object has no attribute 'get_complete_glossary'

Seems like the error appears in here:

lib/python2.7/site-packages/cmsplugin_cascade/bootstrap3/utils.py in reduce_breakpoints

complete_glossary = plugin.get_parent_instance().get_complete_glossary() 

Local vars:
plugin	
Error in formatting: TypeError: __repr__ returned non-string (type __proxy__)

It's only these three plugins, not the others. Are there any thoughts on how to fix this?

**Comment by jrief** [comment]
I'm unable to reproduce this under django-cms==3.2.5

``plugin.get_parent_instance()`` should return the parent of your image, ie. the column. This apparently is not the case. Could you please retry with django-cms==3.2.5.

**Comment by olligopoly** [comment]
Confirmed, this is working with django-cms 3.2.5 but not 3.3.0.

**Comment by jrief** [comment]
ok, then django-cms changed their API or they introduced a regression. I'll have a look at it.

**Comment by jrief** [comment]
@khrizo @olligopoly 
I just pushed a version to Github which should fix this issue. Can you please proceed with testing on django-cms==3.3.0.

**Comment by khrizo** [comment]
Tested on my dev, seems to work. @jrief thank you for the quick fix.
django-cms=3.3.0
djangocms-cascade="0.9.0.dev0"
